version: '3.0'
services:

  registry:
    image: registry:2
    ports:
      - "9001:5001"
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001


  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    ports:
    - 8080:8080
    volumes:
    - ${PWD}/charts:/charts
    environment:
      - PORT=8080
      - DEBUG=1
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/charts

  gitea:
    image: gitea/gitea:1.20-rootless
    restart: always
    volumes:
      - ./gitea/data:/var/lib/gitea
      - ./gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"