apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-app-hr
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-app
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
      version: 0.1.0
  interval: 1m0s