---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: primary-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: mypc.local
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: primary-service
            port:
              number: 5000